// This file maps strategy names to diagram image filenames (placed in /public/strategy-diagrams)
export const strategyDiagrams: Record<string, string> = {
  "Iron Condor": "/strategy-diagrams/iron-condor.svg",
  "Iron Butterfly": "/strategy-diagrams/iron-butterfly.svg",
  "Credit Call Spread": "/strategy-diagrams/credit-call-spread.svg",
  "Credit Put Spread": "/strategy-diagrams/credit-put-spread.svg",
  "Debit Call Spread": "/strategy-diagrams/debit-call-spread.svg",
  "Debit Put Spread": "/strategy-diagrams/debit-put-spread.svg",
  "Long Call": "/strategy-diagrams/long-call.svg",
  "Long Put": "/strategy-diagrams/long-put.svg",
  "Short Call": "/strategy-diagrams/short-call.svg",
  "Short Put": "/strategy-diagrams/short-put.svg",
  "Straddle": "/strategy-diagrams/straddle.svg",
  "Strangle": "/strategy-diagrams/strangle.svg",
  "Call Ratio Spread": "/strategy-diagrams/call-ratio-spread.svg",
  "Put Ratio Spread": "/strategy-diagrams/put-ratio-spread.svg",
  "Calendar Spread": "/strategy-diagrams/calendar-spread.svg",
  "Diagonal Spread": "/strategy-diagrams/diagonal-spread.svg",
  "Condor": "/strategy-diagrams/condor.svg",
  "Butterfly": "/strategy-diagrams/butterfly.svg",
  "Covered Call": "/strategy-diagrams/covered-call.svg",
  "Collar": "/strategy-diagrams/collar.svg",
  "Long Stock": "/strategy-diagrams/long-stock.svg",
  "Short Stock": "/strategy-diagrams/short-stock.svg",
  "Covered Put": "/strategy-diagrams/covered-put.svg",
  "Custom Strategy": "",
};
